### PR TITLE
[bugfix] use profile instead of vehicle for GraphHopper Directions

### PR DESCRIPTION
**Pull request by Serphentas**
See #93

### CODE REVIEW

**Review by nilsnolde — COMMENTED** [review]
Thanks! We also need to update the tests. 

I just realize it's not really good the way we run CI. We try to be conservative with resources and only run CI on review, which is usually fine when we review each other, but not so much for external pull requests. Then you would've immediately gotten feedback from CI that the tests fail. I'll change that again to run on all commits of pull requests.

**Review by nilsnolde — COMMENTED** [review]
Thanks! We also need to update the tests. 

I just realize it's not really good the way we run CI. We try to be conservative with resources and only run CI on review, which is usually fine when we review each other, but not so much for external pull requests. Then you would've immediately gotten feedback from CI that the tests fail. I'll change that again to run on all commits of pull requests.

**Comment by nilsnolde** [comment]
Hmpf, it seems I have no way to trigger CI on this.. Manually didn't work and even after changing the workflow and merging master it doesn't work. Seems like CI configuration isn't re-read after a PR is opened. 

Let me fix the tests, next time it'll work:)

**Comment by nilsnolde** [comment]
That should be it. Ah, now the tests also run, good:)

**Comment by Serphentas** [comment]
Thanks for the quick PR review !

**Comment by nilsnolde** [comment]
no worries! thanks for the PR! 1.2.1 is also published:)

**Pull request merged**
